version: "3.0"

services:

    grconvnet:
      build:
        context: ../grconvnet
        dockerfile: Dockerfile
        args:
          PARENT_IMAGE: ubuntu:focal
          BENCHMARK_REPO: https://github.com/m0dd0/grasping-benchmarks-panda.git
          BENCHMARK_BRANCH: develop
      image: grconvnet
      network_mode: host
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                capabilities: [gpu]
                count: all

    contact_graspnet:
      build:
        context: ../contact_graspnet
        dockerfile: Dockerfile
        args:
          PARENT_IMAGE: nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04
          BENCHMARK_REPO: https://github.com/m0dd0/grasping-benchmarks-panda.git
          BENCHMARK_BRANCH: develop
      image: contact_graspnet
      network_mode: host
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                capabilities: [gpu]
                count: all

    se3dif:
      build:
        context: ../se3dif
        dockerfile: Dockerfile
        args:
          PARENT_IMAGE: nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04
          BENCHMARK_REPO: https://github.com/m0dd0/grasping-benchmarks-panda.git
          BENCHMARK_BRANCH: develop
      image: se3dif
      network_mode: host
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                capabilities: [gpu]
                count: all