checkpoint_dir: scene_test_2048_bs3_hor_sigma_001 # must be locaed in the checkpoints dir in the "original" contact_graspnet repo. See the README.md for more info or use the Docker image.
forward_passes: 1